### ISSUE TITLE
server returns The request is not valid, details: {'additional_parameters': ['unknown field']}

### ISSUE THREAD

**Issue by ed4wg** [CybercentreCanada/assemblyline-service-intezer-dynamic#30]
The service errors with this message. 

```
The intezer web service is most likely down. Indicator: Unable to get the latest analysis for SHA256 7b646dbccb20d5eb8c977735d3d69ea449395f8d79fdbe28bf8988b46e0ede80 due to '400 Client Error: BAD REQUEST for url: https://analyze.intezer.com/api/v2-0/files/7b646dbccb20d5eb8c977735d3d69ea449395f8d79fdbe28bf8988b46e0ede80, server returns The request is not valid, details: {'additional_parameters': ['unknown field']}'."}
```

This is being caused by the `intezer_dynamic.py:ALIntezerApi.get_latest_analysis()` trying to pass `additional_parameters` as a kw argument. See: https://github.com/CybercentreCanada/assemblyline-service-intezer-dynamic/blob/main/intezer_dynamic.py#L152

It should just be:
```
return IntezerApi.get_latest_analysis(
                    self=self,
                    file_hash=file_hash,
                    private_only=private_only,
                    **additional_parameters
                )
```

**Comment by ed4wg** [comment]
Separate, but related. Once that issue is resolved, i believe this issue will pop up. 
```The request is not valid, details: {'should_get_only_private_analysis': ['must be of boolean type']}```

I think the two places where `get_latest_analysis` is called, the `private_only` param should be cast to a boolean.

https://github.com/CybercentreCanada/assemblyline-service-intezer-dynamic/blob/main/intezer_dynamic.py#L515
https://github.com/CybercentreCanada/assemblyline-service-intezer-dynamic/blob/main/intezer_dynamic.py#L556

**Comment by cccs-kevin** [comment]
I'm on a workshop right now, but I will be able to address this issues by the start of the week of Dec 12th :)

**Comment by cccs-kevin** [comment]
@ed4wg, I've made PRs for the fix suggested in https://github.com/CybercentreCanada/assemblyline-service-intezer-dynamic/issues/30#issue-1472881371

I was testing with both private and public deployments of Intezer and did not experience the issue in your second comment https://github.com/CybercentreCanada/assemblyline-service-intezer-dynamic/issues/30#issuecomment-1335271909. This value should be read in from the service configuration as a boolean if you are entering it correctly like this: 
![image](https://user-images.githubusercontent.com/59843993/206299272-adb9d8e6-1407-493d-85ab-a0b89c2a8139.png)
so it sounds like an issue with your service config. 

Let me know if you have any questions :)

**Comment by cccs-kevin** [comment]
Wait, I am seeing that error now... will fix...

**Comment by ed4wg** [comment]
working now - thanks!
