### ISSUE TITLE
404 Client Error

### ISSUE THREAD

**Issue by ed4wg** [CybercentreCanada/assemblyline-service-intezer-dynamic#31]
There are multiple use-cases where the intezer API returns a 404 for a given request. When that happens, this AL4 service is just sleeping and trying again and ends up stuck in an endless loop till the service times out.

This is happening b/c of the way the overridden methods are handling errors in this class: https://github.com/CybercentreCanada/assemblyline-service-intezer-dynamic/blob/main/intezer_dynamic.py#L135

Examples:
https://github.com/CybercentreCanada/assemblyline-service-intezer-dynamic/blob/main/intezer_dynamic.py#L170
https://github.com/CybercentreCanada/assemblyline-service-intezer-dynamic/blob/main/intezer_dynamic.py#L203
https://github.com/CybercentreCanada/assemblyline-service-intezer-dynamic/blob/main/intezer_dynamic.py#L236
https://github.com/CybercentreCanada/assemblyline-service-intezer-dynamic/blob/main/intezer_dynamic.py#L348

In those instances referenced, i would propose that the service catch 404 errors, log that fact, and simply return rather than waiting and trying again over and over. Either that or just do that for any http error that falls into that block.

**Comment by cccs-kevin** [comment]
Hi @ed4wg, the "retrying until the service times out" behaviour is desirable, since Intezer (at least, in private deployments) has the tendency to temporarily drop its REST API when performing imports. 

Therefore the service containers should keep retrying until the REST API comes back up.

Since you are using the public instance, is there a certain error that is causing the 404 that we should return on rather than retrying?

**Comment by ed4wg** [comment]
Hi @cccs-kevin  - The intezer API is simply giving me a 404 in those various scenarios. There's nothing else to key off of other than it returning a 404. There are various scenarios i've observed this happening. 

e.g.
It's trying to call download_file_by_sha256 for a sub-analysis and the API is simply giving a 404 saying it can't give you that sub-file. I can replicate that 404 by calling the api directly. 

Another time i've seen this is when it has found results where a dynamic submission has not run, and when it tries to retrieve the IOCs, it returns a 404. Also related to that is when a file cannot be dynamically executed (from intezers perspective). 

When you say private deployments, i'm assuming you mean an on-prem deployment vs the private instance that Intezer hosts. We use a private instance (not on-prem) and haven't noticed issues like your describing. Maybe that retry behavior could only be run when the `is_on_premise config` is True?

**Comment by cccs-kevin** [comment]
Okay I think then a configurable service-level option that would either retry or fail fast is the solution.

I'm on a workshop right now, but I will be able to address this issues by the start of the week of Dec 12th :)

**Comment by ed4wg** [comment]
@cccs-kevin  - This new param fixed the problem so it won't just wait indefinitely, but it raised some other issues. The methods like `get_iocs`, `get_dynamic_ttps`, `get_sub_analyses_by_id`, etc. now raise the exception to the caller but the caller isn't always gracefully handling it. 

e.g. For some of those callers, it seems like the service could log the exception, but still continue trying to build the results it already has. So rather than erroring the service completely as it's doing now, if those calls fail, just don't build that particular result section and keep going. Or maybe indicate there was an issue with that result section and keep going? 

With the samples I've been submitting with this latest change, i'm seeing more overall service failures than successes. 

Here are a couple of stack traces for some common examples. 
```
File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline_v4_service/common/base.py", line 165, in handle_task
    self.execute(request)
File "/opt/al_service/intezer_dynamic.py", line 536, in execute
    self._process_iocs(analysis_id, file_verdict_map, main_kv_section)
File "/opt/al_service/intezer_dynamic.py", line 657, in _process_iocs
    iocs = self.client.get_iocs(analysis_id)
File "/opt/al_service/intezer_dynamic.py", line 195, in get_iocs
    return IntezerApi.get_iocs(self=self, analyses_id=analysis_id)
File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/intezer_sdk/api.py", line 260, in get_iocs
    raise_for_status(response)
File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/intezer_sdk/api.py", line 60, in raise_for_status
    raise requests.HTTPError(http_error_msg, response=response)
HTTPError: 404 Client Error: NOT FOUND for url: https://analyze.intezer.com/api/v2-0/analyses/ebfdddde-fa4f-4a94-9dbe-2d8440d3d2a1/iocs, server returns Report not found, details: None
```

```
File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline_v4_service/common/base.py", line 165, in handle_task
    self.execute(request)
File "/opt/al_service/intezer_dynamic.py", line 538, in execute
    self._process_ttps(analysis_id, main_kv_section)
File "/opt/al_service/intezer_dynamic.py", line 696, in _process_ttps
    ttps = self.client.get_dynamic_ttps(analysis_id)
File "/opt/al_service/intezer_dynamic.py", line 234, in get_dynamic_ttps
    return IntezerApi.get_dynamic_ttps(self=self, analyses_id=analysis_id)
File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/intezer_sdk/api.py", line 277, in get_dynamic_ttps
    raise_for_status(response)
File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/intezer_sdk/api.py", line 60, in raise_for_status
    raise requests.HTTPError(http_error_msg, response=response)
HTTPError: 404 Client Error: NOT FOUND for url: https://analyze.intezer.com/api/v2-0/analyses/0103c18b-b846-49ee-8c31-a6082d0ef66e/dynamic-ttps, server returns Report not found, details: None
```

**Comment by cccs-kevin** [comment]
@ed4wg thanks for the comment. I think the root of the issue is that for some reason the service is reaching out for analysis IDs that do not exist (https://analyze.intezer.com/api-docs.html#/) `404 Indicates that the resource was not found in Intezer Analyze. For example, a request to get a hash (such as sha256) of a file that was not analyzed`, so if you could find out more about why this is happening it would be much appreciated :) but yes I do agree that 404s should be handled more gracefully, here's a PR to fix this https://github.com/CybercentreCanada/assemblyline-service-intezer-dynamic/pull/37

**Comment by ed4wg** [comment]
Thanks! 

It does look  like there are legitimate times it will return 404s when trying to retrieve the iocs/ttps. e.g. a dynamic submission has not run, and when it tries to retrieve the IOCs or ttps, it returns a 404 as that info is not available. So if a sample is already in the system, but the dynamic analysis has not been run, this will happen. Maybe a way around this is re-submit forcing a new analysis if the dynamic analysis isn't found. Though, there are other times that Intezer fails to dynamically analyze the file just saying it can't do it, so a re-submission won't help in those cases. 

I have seen other errors where it's trying to download a sub-analysis and the API gives a 404. I'll see if i can replicate and reach out to Intezer.

**Comment by cccs-kevin** [comment]
Hmm okay sounds good!

**Comment by ed4wg** [comment]
Following up on this. I found some examples and was able to replicate the issue. Intezer said they are working on a fix to download the files if they are on VT using your configured VT API key. 

However, in looking at `_handle_subanalyses`, there's logic to stop trying to download files if there's even one failure. The `can_we_download_files` is set if the file is not downloaded. Even with Intezer's fix, I suspect there will be files that still fail to download b/c they're not on VT. I realize that logic was probably added to prevent un-necessary api calls if the user is unable to download files, but maybe that should be a configurable service option? So even if there's one failure trying to download one of the sub-analysis files, it will still continue and try to download others, as those others may be available.

**Comment by ed4wg** [comment]
@cccs-kevin - things are running much better now with 4.3.0.stable13. Really appreciate your help and fixes!
